// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeyBuddy
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeyBuddy.c72b947d-6ccc-4046-9b8c-3786421479f7";
        public const string Name = "CodeyBuddy";
        public const string Description = @"Call open AI API and complete the requestCall open AI API and ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Karan Gupta";
        public const string Tags = "";
    }
}
