// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeyBuddy
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CodeyBuddyString = "a8eb0343-b35c-4175-95d8-50549e609ff3";
        public static Guid CodeyBuddy = new Guid(CodeyBuddyString);

        public const string guidCodeyBuddyPackageCmdSetString = "8b0b1a54-4655-4dae-8984-022f82a739f2";
        public static Guid guidCodeyBuddyPackageCmdSet = new Guid(guidCodeyBuddyPackageCmdSetString);

        public const string CodeyBuddySuggestCodeIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eea";
        public static Guid CodeyBuddySuggestCodeIcon = new Guid(CodeyBuddySuggestCodeIconString);

        public const string CodeyBuddyOptimizeCodeIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eeb";
        public static Guid CodeyBuddyOptimizeCodeIcon = new Guid(CodeyBuddyOptimizeCodeIconString);

        public const string CodeyBuddyExplainCodeIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eec";
        public static Guid CodeyBuddyExplainCodeIcon = new Guid(CodeyBuddyExplainCodeIconString);

        public const string CodeyBuddyAddTestsIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eed";
        public static Guid CodeyBuddyAddTestsIcon = new Guid(CodeyBuddyAddTestsIconString);

        public const string CodeyBuddyAskAnythingIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eee";
        public static Guid CodeyBuddyAskAnythingIcon = new Guid(CodeyBuddyAskAnythingIconString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeyBuddySubMenuGroup = 0x1000;
        public const int CodeyBuddyCommandsGroup = 0x1001;
        public const int CodeyBuddySubMenu = 0x2000;
        public const int SuggestCode = 0x0001;
        public const int OptimizeCode = 0x0100;
        public const int ExplainCode = 0x0200;
        public const int AddTests = 0x0300;
        public const int AskAnything = 0x0400;
        public const int cmdidTerminalWindowCommand = 0x0100;
        public const int cmdidTerminalWindowTurboCommand = 0x0101;
        public const int SuggestCodeIcon = 0x0001;
        public const int OptimizeCodeIcon = 0x0001;
        public const int ExplainCodeIcon = 0x0001;
        public const int AddTestsIcon = 0x0001;
        public const int AskAnythingIcon = 0x0001;
    }
}